-- MySQL Script generated by MySQL Workbench
-- 04/10/15 11:50:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vt3_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vt3_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vt3_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `vt3_db` ;


-- -----------------------------------------------------
-- Table `vt3_db`.`genotype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vt3_db`.`genotype` (
  `genotype_id` INT(11) NOT NULL AUTO_INCREMENT,
  `individual_id` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `snp` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `call` VARCHAR(3) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `project_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`genotype_id`),
  INDEX `fk_genotype_2_idx` (`project_id` ASC),
  INDEX `fk_genotype_1_idx` (`individual_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5969
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `vt3_db`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vt3_db`.`group` (
  `group_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `indiv_list` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `project_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `vt3_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vt3_db`.`user` (
  `user_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `email` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `password` CHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`user_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `vt3_db`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vt3_db`.`project` (
  `project_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `description` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `owner` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_project_1_idx` (`owner` ASC),
  CONSTRAINT `fk_project_1`
    FOREIGN KEY (`owner`)
    REFERENCES `vt3_db`.`user` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `vt3_db`.`individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vt3_db`.`individual` (
  `individual_id` INT(11) NULL DEFAULT NULL,
  `old_id` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `new_id` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `project_id` INT(11) NOT NULL,
  `gender` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`new_id`, `project_id`),
  INDEX `fk_individual_1_idx` (`project_id` ASC),
  INDEX `INDEX` (`new_id` ASC),
  CONSTRAINT `fk_individual_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `vt3_db`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `vt3_db`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vt3_db`.`log` (
  `idlog` INT(11) NOT NULL AUTO_INCREMENT,
  `timestamp` INT(11) NULL DEFAULT NULL,
  `user_id` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `action` VARCHAR(400) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`idlog`),
  INDEX `fk_log_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_log_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `vt3_db`.`user` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 587
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `vt3_db`.`membership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vt3_db`.`membership` (
  `user_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `project` INT(11) NOT NULL,
  PRIMARY KEY (`user_name`, `project`),
  CONSTRAINT `fk_Membership_1`
    FOREIGN KEY (`user_name`)
    REFERENCES `vt3_db`.`user` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `vt3_db`.`phenotype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vt3_db`.`phenotype` (
  `phenotype_id` INT(11) NOT NULL AUTO_INCREMENT,
  `individual_id` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `value` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `project_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`phenotype_id`),
  INDEX `fk_phenotype_1_idx` (`individual_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 17886
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
